config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  devise_for :models

  scope "(:locale)", locale: /en|de|fr/ do
    root 'static_pages#welcome'

    resources :questions
    resources :arguments
    resources :images
    get '/adminpanel', to: 'arguments#adminpanel'
    get '/visits', to: 'static_pages#visits'
    get '/contact', to: 'static_pages#contact', as: 'contact'
    get '/contribute', to: 'static_pages#contribute', as: 'contribute'
    get '/use', to: 'static_pages#use', as: 'use'
    get '/overview', to: 'static_pages#overview', as: 'overview'
    get '/impressum', to: 'static_pages#impressum', as: 'impressum'
  end



  post "/arguments/publishargument/:id", to: 'arguments#publishargument', as: 'publish_argument'
  post "/questions/publishquestion/:id", to: 'questions#publishquestion', as: 'publish_question'

  post "/arguments/submitsuggestion/:id", to: 'arguments#submitsuggestion', as: 'submit_suggestion'

  post "/arguments/search", to: 'arguments#search'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def welcome

  end

  def overview
    @questions_with_few_arguments = Question.published.fewer_arguments_than(2)
  end

  def visits

  end

  def contact

  end

  def contribute

  end

  def use

  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_contribute.de.html.erb
<div class="rounded greyish-bg p-4 mb-1">
    <h3 class="text-center"><%= t('contribute') %></h3>
    <hr />
<p>
  <b>Füge neue Fragen hinzu.</b>
  <br>(Bitte überprüfe, ob nicht bereits ähnliche Fragen vorhanden sind).
  <br>
  <%= link_to t('submit_a_new_question'), new_question_path, class: "btn btn-success btn-lg my-2 multilinebutton" %>
</p>
<hr />
<p>
  <b>Füge neue Argumente hinzu.</b>
  <br>
    <%= link_to t('show_questions_with_no_or_few_arguments'), overview_path, class: "btn btn-success btn-lg my-2 multilinebutton" %>
</p>
<hr />
<p>
<b>Übersetze bestehende Fragen und Antworten in andere Sprachen.</b>
</p>
<hr />
<p>
  <b>Feedback geben.</b>
  <br>Verbesserungsvorschläge? Fehlende Feautures? Fragen? Designvorschläge?
  <br>
  <%= link_to t('contact'), contact_path, class: "btn btn-success btn-lg my-2 multilinebutton" %>
</p>
</div>

app/views/static_pages/_contribute.en.html.erb
<div class="rounded greyish-bg p-4 mb-1">
    <h3 class="text-center"><%= t('contribute') %></h3>
    <hr />
<p>
  <b>Submit new questions</b>.
  <br>(Please make sure that a similar question does not already exist).
  <br>
  <%= link_to t('submit_a_new_question'), new_question_path, class: "btn btn-success btn-lg my-2 multilinebutton" %>
</p>
<hr />
<p>
  <b>Submit new arguments to questions.</b>
  <br>
    <%= link_to t('show_questions_with_no_or_few_arguments'), overview_path, class: "btn btn-success btn-lg my-2 multilinebutton" %>
</p>
<hr />
<p>
<b>Translate existing questions and answers into new languages.</b>
</p>
<hr />
<p>
  <b>Give feedback.</b>
  <br>Bad design? Missing features? Missing language? Suggestion for improvements?
  <br>
  <%= link_to t('contact'), contact_path, class: "btn btn-success btn-lg my-2 multilinebutton" %>
</p>
</div>

app/views/static_pages/_use.en.html.erb
<div class="rounded greyish-bg p-4 mb-1">
  <h3 class="text-center"><%= t('use_this_database') %></h3>
  <hr />
    <p>
      <b><%= t('browse_question_and_arguments') %>.</b> <br>
       <%= link_to t('browse_question_and_arguments'), arguments_path, class: "btn btn-success btn-lg my-2 multilinebutton" %>
     </p>
     <hr />
       <p>
      <b><%= t('download_curent_database_in_different_formats') %></b>
       <br> <%= link_to 'Download - PDF', arguments_path(:format => :pdf), class: "btn btn-success btn-lg multilinebutton my-2", :data => { :buttonclick => 'pdf-all'} %>
       <br> <%= link_to 'Download - CSV', arguments_path(:format => :csv), class: "btn btn-success btn-lg multilinebutton my-2", :data => { :buttonclick => 'csv-all'} %>
       <br> <%= link_to 'Download - JSON', arguments_path(:format => :json), class: "btn btn-success btn-lg multilinebutton my-2", :data => { :buttonclick => 'json-all'} %>
     </p>
     <hr />
     <p>
      <b><%= t('access_this_database_via_api') %></b> <br>
      <%= link_to t('how_to_use_api'), arguments_path, class: "btn btn-success btn-lg my-2 multilinebutton" %>
  </p>
  <hr />
  <p>
        <b><%= t('embed_or_share_questions_and_arguments_via_social_media') %></b><br>
         <%= link_to t('how_to_share_via_social_media'), arguments_path, class: "btn btn-success btn-lg my-2 multilinebutton" %>

</p>
</div>

<hr />

<script>

    $( document ).ready(function() {

        $("[data-buttonclick]").click(function(){
            ahoy.track("buttonclick: " + $(this).attr( "data-buttonclick" ), {language: "JavaScript"});
        });
    });
</script>

app/views/static_pages/contact.de.html.erb
<div class="jumbotron">
  <div class="row">
    <div class="col-12 text-justify">
      <h1 class="text-center">
        <%= t('contact') %>
      </h1>
      <hr />
    </div>
    <div class="col-12 text-center mb-5 animated-divs">
      <p>
        Feedback? Verbesserungsvorschläge? Fragen? Designvorschläge? Oder einfach nur ein bisschen chatten?
      </p>
      <p>
        Einfach schreiben!
      </p>
      <button type="button" data-target="contact" class="btn btn-success btn-lg btn-block multilinebutton"><%= t('contact') %></button>
      <div id="contact" class="hiddenfromstart  text-center d-none m-5">
        <p>
          <b>Mail: </b><a href="mailto:sandro.raess@philosophie.ch">sandro.raess_at_philosophie.ch</a><br>
          <b>Skype: </b>crystal-metal<br>
        </p>
      </div>
      <hr />
    </div>
</div>
</div>

<script>

    $( document ).ready(function() {

        $(".btn").click(function(){
            console.log($(this).attr( "data-target" ));
            toggleButton($("#" + $(this).attr( "data-target" )));
            ahoy.track("contact: " + $(this).attr( "data-target" ), {language: "JavaScript"});
        });

        function toggleButton(div) {
                if (div.hasClass("d-none")){
                    div.removeClass("animated zoomOut");
                    div.removeClass("d-none").addClass("animated fadeIn");
                    $('html, body').animate({
                        scrollTop:div.offset().top
                    },'slow');
                } else {
                    div.removeClass("animated fadeIn");
                    div.addClass("animated zoomOut").delay(500).queue(function(){
                        div.addClass("d-none").dequeue();
                    });
                }
        }
    });



</script>

app/views/static_pages/contact.en.html.erb
<div class="jumbotron">
  <div class="row">
    <div class="col-12 text-justify">
      <h1 class="text-center">
        <%= t('contact') %>
      </h1>
      <hr />
    </div>
    <div class="col-12 text-center mb-5 animated-divs">
      <p>
        Feedback? Suggestions for improvements? Questions? Design proposals? Or just wanna chat?
      </p>
      <p>
        Don't hesitate and contact me!
      </p>
      <button type="button" data-target="contact0" class="btn btn-success btn-lg btn-block multilinebutton"><%= t('contact') %></button>
      <div id="contact0" class="hiddenfromstart  text-center d-none m-5">
        <p>
          <b>Mail: </b><a href="mailto:sandro.raess@philosophie.ch">sandro.raess_at_philosophie.ch</a><br>
          <b>Skype: </b>crystal-metal<br>
        </p>
      </div>
      <hr />
    </div>
</div>
</div>

<script>

    $( document ).ready(function() {

        $(".btn").click(function(){
            console.log($(this).attr( "data-target" ));
            toggleButton($("#" + $(this).attr( "data-target" )));
            ahoy.track("hire: " + $(this).attr( "data-target" ), {language: "JavaScript"});
        });

        function toggleButton(div) {
                if (div.hasClass("d-none")){
                    div.removeClass("animated zoomOut");
                    div.removeClass("d-none").addClass("animated fadeIn");
                    $('html, body').animate({
                        scrollTop:div.offset().top
                    },'slow');
                } else {
                    div.removeClass("animated fadeIn");
                    div.addClass("animated zoomOut").delay(500).queue(function(){
                        div.addClass("d-none").dequeue();
                    });
                }
        }
    });



</script>

app/views/static_pages/contact.html.erb
<div class="jumbotron">
  <div class="row">
    <div class="col-12 text-justify">
      <h1 class="text-center">
        Contact
      </h1>
      <hr />
    </div>
    <div class="col-12 text-center mb-5 animated-divs">
      <p>
        Bad design? Missing features? Missing languages? Suggestions for improvements? Any cool ideas? Or just wanna chat?
      </p>
      <button type="button" data-target="contact0" class="btn btn-success btn-lg btn-block multilinebutton"><%= t('give_feedback') %></button>
      <div id="contact0" class="hiddenfromstart  text-center d-none m-5">
        <p>
          <b>Mail: </b><a href="mailto:sandro.raess@philosophie.ch">sandro.raess_at_philosophie.ch</a><br>
          <b>Skype: </b>crystal-metal<br>
        </p>
      </div>
      <hr />
    </div>
</div>
</div>

<script>

    $( document ).ready(function() {

        $(".btn").click(function(){
            console.log($(this).attr( "data-target" ));
            toggleButton($("#" + $(this).attr( "data-target" )));
            ahoy.track("hire: " + $(this).attr( "data-target" ), {language: "JavaScript"});
        });

        function toggleButton(div) {
                if (div.hasClass("d-none")){
                    div.removeClass("animated zoomOut");
                    div.removeClass("d-none").addClass("animated fadeIn");
                    $('html, body').animate({
                        scrollTop:div.offset().top
                    },'slow');
                } else {
                    div.removeClass("animated fadeIn");
                    div.addClass("animated zoomOut").delay(500).queue(function(){
                        div.addClass("d-none").dequeue();
                    });
                }
        }
    });



</script>

app/views/static_pages/contribute.html.erb
<div class="jumbotron jumbotron-bg">
  
<%=  render partial: "static_pages/contribute" %>

</div>

app/views/static_pages/impressum.html.erb
<div class="jumbotron">
<h1> Impressum & Datenschutz </h1>
<p>
  Sandro Räss <br>
  Fohrenbühlstrasse 4 <br>
  Diessenhofen <br>
 </p>

<p style="text-align: justify;"><strong>Haftungsausschluss</strong><br> Weder Sandro Räss noch die ausgewiesenen  AutorInnen übernehmen Gewähr hinsichtlich der inhaltlichen Richtigkeit, Genauigkeit, Aktualität, Zuverlässigkeit und Vollständigkeit der Informationen.<br> Haftungsansprüche gegen den Autor wegen Schäden materieller oder immaterieller Art, welche aus dem Zugriff oder der Nutzung bzw. Nichtnutzung der veröffentlichten Informationen, durch Missbrauch der Verbindung oder durch technische Störungen entstanden sind, werden ausgeschlossen.<br> Alle Angebote sind unverbindlich. Der Autor behält es sich ausdrücklich vor, Teile der Seiten oder das gesamte Angebot ohne gesonderte Ankündigung zu verändern, zu ergänzen, zu löschen oder die Veröffentlichung zeitweise oder endgültig einzustellen.</p>
<p style="text-align: justify;"> </p>
<p style="text-align: justify;"><strong>Haftung für Links</strong><br> Verweise und Links auf Webseiten Dritter liegen ausserhalb unseres Verantwortungsbereichs. Es wird jegliche Verantwortung für solche Webseiten abgelehnt. Der Zugriff und die Nutzung solcher Webseiten erfolgen auf eigene Gefahr des Nutzers oder der Nutzerin.</p>
<p style="text-align: justify;"> </p>
<p style="text-align: justify;"><strong>Urheberrechte</strong><br> Die Urheber- und alle anderen Rechte an Inhalten, Bildern, Fotos oder anderen Dateien auf der Website gehören den speziell genannten Rechtsinhabern, vor allem der genannten AutorInnen.</p>
<p style="text-align: justify;"> </p>
<p style="text-align: justify;"><strong>Datenschutz</strong><br> Gestützt auf Artikel 13 der schweizerischen Bundesverfassung und die datenschutzrechtlichen Bestimmungen des Bundes (Datenschutzgesetz, DSG) hat jede Person Anspruch auf Schutz ihrer Privatsphäre sowie auf Schutz vor Missbrauch ihrer persönlichen Daten. Wir halten diese Bestimmungen ein. Persönliche Daten werden streng vertraulich behandelt und weder an Dritte verkauft noch weiter gegeben.<br> In enger Zusammenarbeit mit unseren Hosting-Providern bemühen wir uns, die Datenbanken so gut wie möglich vor fremden Zugriffen, Verlusten, Missbrauch oder vor Fälschung zu schützen.<br> Beim Zugriff auf unsere Webseiten werden folgende Daten in Logfiles gespeichert: IP-Adresse, Datum, Uhrzeit, Browser-Anfrage und allg. übertragene Informationen zum Betriebssystem resp. Browser. Diese Nutzungsdaten bilden die Basis für statistische, anonyme Auswertungen, so dass Trends erkennbar sind, anhand derer wir unsere Angebote entsprechend verbessern können.</p>
</div>

app/views/static_pages/overview.html.erb
<div class="jumbotron">
  <h3><%= t('overview') %></h3>
  <%=  render partial: "arguments/questionlist", locals: {questions: @questions_with_few_arguments} %>
</div>

app/views/static_pages/use.html.erb
<div class="jumbotron jumbotron-bg">

<%=  render partial: "static_pages/use" %>

</div>

app/views/static_pages/visits.html.erb
<div class="jumbotron">
<%= geo_chart Ahoy::Visit.group(:country).count %>
<br>
<%= bar_chart Ahoy::Visit.group(:country).count %>
<br>
<%= bar_chart Ahoy::Visit.group(:region).count %>
<br>
<%= line_chart Ahoy::Visit.group_by_day(:started_at).count %>
<br>
Visits total: <%= Ahoy::Visit.all.count %>
<br>

<%= bar_chart Ahoy::Event.select(:visit_id).distinct.group(:properties).count, height: "1000px" %>

<br>
Arguments: <br>
<%= bar_chart Ahoy::Event.select(:visit_id).where_props(controller: "arguments").group(:properties).count, height: "1000px" %>

<br>
Static Pages: <br>
<%= bar_chart Ahoy::Event.select(:visit_id).distinct.where_props(controller: "static_pages").group(:properties).count, height: "1000px" %>

<br>
Kontakt: <br>
<%= bar_chart Ahoy::Event.select(:visit_id).distinct.where("name like ?", "hire:%").group(:name).count %>
<br>
Buttonclick: <br>
<%= bar_chart Ahoy::Event.select(:visit_id).distinct.where("name like ?", "buttonclick:%").group(:name).count %>
</div>

app/views/static_pages/welcome.de.html.erb
<div class="jumbotron jumbotron-bg">
    <h2>
      Lasst uns besser zu Tieren sein.
    </h2>
    <hr />
    <p>
      Veggie-Database ist eine Datenbank von Argumenten für die Verbesserung des Tierschutzes.
    </p>
    <p>
      Hier ist ein kurzes Beispiel:
    </p>
        <%=  render partial: "arguments/questionshowcase", locals: {question: Question.first, arguments: Argument.where(id: Question.first.arguments.first.id), show: false } %>

        <hr />
<%=  render partial: "static_pages/use" %>

<%=  render partial: "static_pages/contribute" %>

</div>

app/views/static_pages/welcome.en.html.erb
<div class="jumbotron jumbotron-bg">
    <h2>
      Let's be better to animals.
    </h2>
    <hr />
    <p>
      This is a database of arguments that aim to improve animal welfare.
    </p>
    <p>
      Here is a short example:
    </p>
        <%=  render partial: "arguments/questionshowcase", locals: {question: Question.first, arguments: Argument.where(id: Question.first.arguments.first.id), show: false } %>

        <hr />
<%=  render partial: "static_pages/use" %>

<%=  render partial: "static_pages/contribute" %>

</div>

app/views/static_pages/welcome.html.erb
<div class="jumbotron jumbotron-bg">
    <h2>
      Let's be better to animals.
    </h2>
    <hr />
    <p>
      This is a database of arguments that aim to improve animal welfare.
    </p>
    <p>
      Here is a short example:
    </p>
        <%=  render partial: "arguments/questionshowcase", locals: {question: Question.first, arguments: Argument.where(id: Question.first.arguments.first.id), show: false } %>

        <hr />
<%=  render partial: "static_pages/use" %>

<%=  render partial: "static_pages/contribute" %>

</div>