config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  devise_for :models

  scope "(:locale)", locale: /en|de|fr/ do
    root 'static_pages#welcome'

    resources :questions
    resources :arguments
    resources :images
    get '/adminpanel', to: 'arguments#adminpanel'
    get '/visits', to: 'static_pages#visits'
    get '/contact', to: 'static_pages#contact', as: 'contact'
    get '/contribute', to: 'static_pages#contribute', as: 'contribute'
    get '/use', to: 'static_pages#use', as: 'use'
    get '/overview', to: 'static_pages#overview', as: 'overview'
    get '/impressum', to: 'static_pages#impressum', as: 'impressum'
  end



  post "/arguments/publishargument/:id", to: 'arguments#publishargument', as: 'publish_argument'
  post "/questions/publishquestion/:id", to: 'questions#publishquestion', as: 'publish_question'

  post "/arguments/submitsuggestion/:id", to: 'arguments#submitsuggestion', as: 'submit_suggestion'

  post "/arguments/search", to: 'arguments#search'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/argument.rb
class Argument < ApplicationRecord

  require 'csv'

  validates :title, presence: true
  validates :argument, presence: true

  before_save :sanitize_url

  extend FriendlyId
  friendly_id :title, use: :slugged

  include PgSearch

  belongs_to :question, optional: true

  pg_search_scope :basic_search_for,
                  :against => [:argument, :title, :author],
                  using: { tsearch: { any_word: true, prefix: true } }


  include PgSearch

  multisearchable :against => [:argument, :title, :author],
                  :if => lambda { |record| record.published == true }

  scope :published, -> { where(published: true) }
  scope :unpublished, -> { where(published: false) }

  def question
    parent.question
  end

  def clean_argument
    ActionController::Base.helpers.strip_tags(argument)
  end

  def parent
    Question.find(self.question_id)
  end

  def languagefull
    #Language.find_by_abbreviation(self.language).name
    I18n.t(self.language.to_s)
  end

  def hyperlink
    #host = Rails.configuration.host.to_s
    #Rails.application.routes.url_helpers.argument_url(self, :id => self.id, :only_path => false, :host => host)
    Rails.configuration.host.to_s + I18n.locale.to_s + "/arguments/" + slug
    #Rails.application.routes.url_helpers.arguments_url
    #Rails.application.routes.url_helpers.arguments_url(:host => Rails.configuration.host.to_s)
  end

  def length
    clean_argument.length
  end

  def self.to_csv
  #attributes = %w{question title clean_argument author, language, link}
  attributes = [Question.model_name.human, Argument.human_attribute_name("title"), Argument.human_attribute_name("argument"), Argument.human_attribute_name("author"), Argument.human_attribute_name("url"), Argument.human_attribute_name("language"), "Link"]
    CSV.generate(headers: true) do |csv|
    csv << attributes
      all.each do |argument|
        csv << [argument.question, argument.title, argument.clean_argument, argument.author, argument.url, I18n.t(argument.language.to_s), argument.hyperlink]
      end
    end
  end

  private
  def sanitize_url
    if !self.url.blank?
      self.url = "http://#{self.url}" unless self.url =~ /^https?:\/\//
    end
  end

end

app/controllers/arguments_controller.rb
class ArgumentsController < ApplicationController
  before_action :set_argument, only: [:submitsuggestion, :publishargument, :show, :edit, :update, :destroy]
  before_action :allowed?, only: [:edit, :update, :destroy, :adminpanel]

  def adminpanel
    @arguments = Argument.all
    @questions = Question.all
    @unpublishedarguments = Argument.unpublished
    @unpublishedquestions = Question.unpublished
  end

  def submittranslation

  end

  def search
    search = params[:search]

    if search.nil? || search.empty?
      #@arguments = Argument.published
      @questions = Question.all
      @arguments = Argument.none
    else
      #@arguments = Argument.published.where("question ILIKE ? OR quickanswer ILIKE ? OR longanswer ILIKE ?", "%#{search}%", "%#{search}%", "%#{search}%")
      #@pdfs = Pdf.search_title_file_name_url(search)
      #@arguments = Argument.published.basic_argument_search_for(search)
      #results = PgSearch.multisearch(search)
      #arguments = results.where(searchable_type: "Argument")
      #questions = results.where(searchable_type: "Question")
      #arguments_ids = arguments
      questions = Question.published.basic_search_for(search)
      @arguments = Argument.published.basic_search_for(search)

      questions = questions + Question.find(@arguments.pluck(:question_id).uniq)
      @questions = questions.uniq

    end

    respond_to do |format|
      format.html { render partial: "searchresults" }
    end
  end

  def submitsuggestion
    original = @argument
    @argument = original.dup

    render "new"
  end


  def publishargument

    if @argument.published == true
      @argument.update(published: false)
    else
      @argument.update(published: true)
    end

    redirect_to adminpanel_path
  end
  # GET /arguments
  # GET /arguments.json
  def index
    #@arguments = Argument.published
    @questions = Question.all
    @arguments = Argument.none

    respond_to do |format|
      format.html
      format.csv { send_data Argument.all.to_csv, filename: "arguments-#{Date.today}.csv" }
      format.json
      format.pdf do
        @arguments = Argument.all
        render pdf: "arguments-#{Date.today}.csv",
        template: "arguments/pdf.html.erb",
        layout: 'pdf.html'
      end
    end

  end

  # GET /arguments/1
  # GET /arguments/1.json
  def show
    @title = @argument.title
  end

  # GET /arguments/new
  def new
      @argument = Argument.new
      @question = params[:question]
    logger.debug @question
  end

  # GET /arguments/1/edit
  def edit
  end

  # POST /arguments
  # POST /arguments.json
  def create
    @argument = Argument.new(argument_params)

    respond_to do |format|
      if @argument.save
        format.html { redirect_to @argument, notice: 'Argument was successfully created. Moderation will take 2-3 days.' }
        format.json { render :show, status: :created, location: @argument }
      else
        format.html { render :new }
        format.json { render json: @argument.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /arguments/1
  # PATCH/PUT /arguments/1.json
  def update
    respond_to do |format|
      if @argument.update(argument_params)
        format.html { redirect_to @argument, notice: 'Argument was successfully updated.' }
        format.json { render :show, status: :ok, location: @argument }
      else
        format.html { render :edit }
        format.json { render json: @argument.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /arguments/1
  # DELETE /arguments/1.json
  def destroy
    @argument.destroy
    respond_to do |format|
      format.html { redirect_to arguments_url, notice: 'Argument was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def impressum

  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_argument
      #@argument = Argument.find(params[:id])
      @argument = Argument.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def argument_params
      params.require(:argument).permit(:argument, :title, :question_id, :author, :language, :url)
    end
end

app/helpers/arguments_helper.rb
module ArgumentsHelper
end

app/views/arguments/_argument.html.erb
<div class="rounded p-3 mb-3 jumbotron-bg">

<p>
  <div class="argumenttitle text-center rounded p-1"><%= link_to argument.title, argument_path(argument) %>
  <br>
  <br>
  <%= social_share_button_tag(argument.question, 'data-facebook-title' => argument.question, 'data-twitter-title' => argument.question.to_s + " " + argument.title.to_s, :url => argument.hyperlink, :desc => argument.question) %>
</div>

</p>
<hr />
      <%=  render partial: "arguments/sanitizedargument", locals: {argument: argument} %>

<hr />
      <%=  render partial: "arguments/author", locals: {argument: argument} unless argument.author.blank? %>

      <%=  render partial: "arguments/url", locals: {argument: argument} unless argument.url.blank? %>
</div>

app/views/arguments/_argumentsearchform.html.erb
<%= form_tag(arguments_path, method: "get", remote: true, class: "form-group") do %>
    <%= text_field_tag(:search, nil, placeholder: t('browse_question_and_arguments'), autocomplete: :off, class: "form-control") %>
    <%= submit_tag("Search", id: "triggersearch", class: "invisible") %>
<% end %>

<div id="argumentresults">
  <%= render "searchresults" %>
</div>

<div class="rounded greyish-bg mt-5 text-center">
  <%= t('found_nothing') %> <%= link_to t('submit_a_new_question'), new_question_path, class: "btn btn-success btn-lg my-2 multilinebutton" %>
</div>

<script>
    $(document).ready(function(){

        $( "#search" ).keyup(function() {
            $( "#argumentresults" ).html( "<div class=\"mx-auto loader\"></div>" );

            $.ajax({
                method: "POST",
                headers: { 'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content') },
                url: "/arguments/search",
                data: { search: $( "#search" ).val() }
            }).done(function(result) {
                $("#argumentresults").html(result);
            });



        });

    });
</script>

app/views/arguments/_author.html.erb
<p>
<b><%= Argument.human_attribute_name("author") %>: </b> <u><%= argument.author %></u>
</p>

app/views/arguments/_diff.html.erb
<%= render partial: "diff", locals: {original: Argument.find(@argument.argument_id), suggestion: @argument} if @argument.argument_id && !current_user.nil? %>

<div class="top d-none">
  <strong>Context size (optional):</strong> <input type="text" id="contextSize" value="" />
</div>
<div class="textInput d-none">
  <h2>Base Text</h2>
  <textarea id="baseText">
   <%= strip_tags(original.longanswer) %>
  </textarea>
</div>
<div class="textInput spacer d-none">
  <h2>New Text</h2>
  <textarea id="newText">
   <%= strip_tags(suggestion.longanswer) %>
  </textarea>
</div>
<div class="viewType">
  <input type="radio" name="_viewtype" id="sidebyside" onclick="diffUsingJS(0);" /> <label for="sidebyside">Side by Side Diff</label>
  &nbsp; &nbsp;
  <input type="radio" name="_viewtype" id="inline" onclick="diffUsingJS(1);" /> <label for="inline">Inline Diff</label>
</div>
<div id="diffoutput"> </div>

<script type="text/javascript">

    function diffUsingJS(viewType) {
        "use strict";
        var byId = function (id) { return document.getElementById(id); },
            base = difflib.stringAsLines(byId("baseText").value),
            newtxt = difflib.stringAsLines(byId("newText").value),
            sm = new difflib.SequenceMatcher(base, newtxt),
            opcodes = sm.get_opcodes(),
            diffoutputdiv = byId("diffoutput"),
            contextSize = byId("contextSize").value;

        diffoutputdiv.innerHTML = "";
        contextSize = contextSize || null;

        diffoutputdiv.appendChild(diffview.buildView({
            baseTextLines: base,
            newTextLines: newtxt,
            opcodes: opcodes,
            baseTextName: "Base Text",
            newTextName: "New Text",
            contextSize: contextSize,
            viewType: viewType
        }));
    }

    diffUsingJS(0);

</script>

app/views/arguments/_form.html.erb
<div class="jumbotron jumbotron-bg">

<p class="text-center">
  <i>
    <% question_id = @argument.question_id || @question %>
    <%= Question.find(question_id).question %>
  </i>
</p>

  <hr />

<%= simple_form_for(@argument) do |f| %>

      <% if argument.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(argument.errors.count, "error") %> prohibited this argument from being saved:</h2>

            <ul>
              <% argument.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
              <% end %>
            </ul>
          </div>
      <% end %>
    <%= f.input :title %>
    <%= f.label :argument %>
    <%= f.text_area :argument, :class => "tinymce", :rows => 15, :cols => 120, id: :argument_argument %>
    <br>
    <%= f.input :author %>
    <%= f.input :language, collection: Language.all, value_method: :abbreviation, selected: I18n.locale.to_s %>
    <%= f.hidden_field :question_id, value: question_id %>
    <%= f.input :url, label: t('url-input-form') %>
    <%= f.button :submit, t('create'), class: "btn btn-success btn-lg" %>
<% end %>

<%= tinymce %>

</div>

app/views/arguments/_oldform.html.erb
<div class="jumbotron jumbotron-bg">

<%= simple_form_for(@argument) do |f| %>
    <%= f.input :author %>
    <%= f.input :language, collection: Language.all, value_method: :abbreviation, selected: "English" %>
    <%= f.text_area :argument, :class => "tinymce", :rows => 20, :cols => 120, id: :argument_argument %>
    <%= f.button :submit %>
<% end %>

</div>

<div class="jumbotron jumbotron-bg">

<%= form_with(model: argument, local: true) do |form| %>
  <% if argument.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(argument.errors.count, "error") %> prohibited this argument from being saved:</h2>

      <ul>
      <% argument.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


    <div class="field">
      <h4>Author (e.g. <b>"Peter Singer"</b>, <b>"Klaus Petrus"</b> or <b>"Anonymous"</b>).</h4>
      <%= form.text_field :author, id: :argument_author, class: "form-control"  %>
    </div>
    <br>

    <div class="field">
      <h4>Language</h4>
      <%= form.collection_select :language, Language.all, :abbreviation, :name, {}, {class: "form-control"} %>
    </div>
    <br>

  <div class="field">
    <h4>Argument</h4>

  </div>

    <br>
    <div class="field">
      <h4>URLs, sources, further literature</h4>
      <%= form.text_field :urls, multiple: true, class: "form-control" %>
      <%= form.text_field :urls, multiple: true, class: "form-control"  %>
      <%= form.text_field :urls, multiple: true, class: "form-control"  %>
    </div>

    <%= form.hidden_field :question_id, value: 1 %>

    <div class="actions">
    <%= form.submit %>
  </div>
<% end %>


<%= tinymce %>

</div>

app/views/arguments/_questionlist.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col-8">Question</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% questions.each do |question| %>
    <tr>
      <td><%= question.question %></td>
      <td><%= link_to "Submit new argument", new_argument_path(question: question.id), class: "btn btn-success multilinebutton" %></td>
    </tr>
    <% end %>

  </tbody>
</table>

app/views/arguments/_questionshowcase.html.erb
        <div class="rounded greyish-bg p-4 mb-1">
          <p class="text-center">
            <i><%= link_to question.question, question_path(question) %></i>
          </p>

          <hr />

          <p>
          <% if !arguments.empty? %>

            <% arguments.each do |argument| %>

              <%=  render partial: "arguments/argument", locals: {argument: argument} %>
            <% end %>

         <% end %>
          </p>

          <p>
            <% if question.arguments.empty? %>
              <%= t('no_arguments_yet') %> <%= link_to t('submit_a_new_argument'), new_argument_path(question: question.id), class: "btn btn-success" %>
              <% elsif show == true %>
              <%= link_to t('submit_a_new_argument'), new_argument_path(question: question.id), class: "btn btn-success" %>
              <% elsif question.arguments.count != arguments.count %>
                <%= link_to t('view_all_arguments'), question_path(question), class: "btn btn-success" %>
          <% end %>
            </p>
        </div>

app/views/arguments/_sanitizedargument.html.erb
<div class="underlinelinks">
  <%= sanitize argument.argument, attributes: %w(style href src) %>
</div>

app/views/arguments/_url.html.erb
<b><%= Argument.human_attribute_name("url") %>: </b>
<u>
  <%= link_to argument.url, argument.url, target: "_blank" %><br>
</u>

app/views/arguments/ablage.html.erb
<div class="jumbotron jumbotron-bg">
    <h2>
      Let's be better to animals.
    </h2>
    <hr />
    <p>
      This is a database of arguments that aim to improve animal welfare.
    </p>
    <p>
      Here is an example:
    </p>
    <p>
    <strong>
      Why not eat meat?
    </strong>
    <br>
    Because the meat industry <b>is mostly cruel to animals</b>.
    The meat industry <b>isn't interested in animal welfare</b>, it is <b>interested in making profit</b>.
    Making profit and treating animals well is often <b>incompatible</b> because treating animals well is demanding.
    What do you think does the meat industry care more about? Good salaries or animal welfare?
      https://www.rollingstone.com/feature/belly-beast-meat-factory-farms-animal-activists
    </p>
  https://www.srf.ch/kultur/gesellschaft-religion/das-tier-und-wir/tierisch-gute-argumente-gegen-den-fleischkonsum

  <hr />
    <h3>Contribute</h3>
    <p>
      You can contribute to this database in several ways.
      <ul>
        <li>
          You can add new questions: <%= link_to "Submit new question", new_question_path, class: "btn btn-sm btn-success" %>
          <br>
          Please make sure that a similar question does not already exist.
        </li>
        <li>
          You can submit new arguments to questions.<br>
          Here you can see all questions that don't have any arguments yet: LINK
          <br>
        </li>
        <li>
          Translate existing questions and answers into new languages.
        </li>
        <li>
          Give feedback: Design bad? Missing features?
        </li>
      </ul>
    </p>
  <%= link_to "You can submit your own questions and arguments", new_argument_path %>

  <p>
    You can submit your own questions and arguments.
    Go to "Submit" and enter your suggestion or suggest a better answer to an existing question.
  </p>

  <h3>Use this database</h3>
  <p>
    Browse here.
  </p>
  <p>
    You can download the current database as csv-file here: Download
  </p>
  <p>
    You can access this database via API. Take a look here: How to use this database
  </p>
  <p>
    Social Media
  </p>

  <p>
  <h3>
    Rules
  </h3>
  Don't use esoteric arguments like "killing animals will have a bad effect on your karma!".
  If we want people to treat animals well, we shouldn't insult their intelligence.
  </p>


</div>

<p>
<h3>
  Guidelines
</h3>
Let's face it. Most people don't give a shit about animal suffering.
If we want them to care about animal suffering, we have to give them good reasons.
</p>
<p>
  There are also different kinds of people and therefore different kinds of reasons or arguments that appeal to them.
</p>
<p>
  But I don't think that any kind of reason that may motivate some people to care about animal suffering is automatically a good one.
</p>
<p>
  For example, arguments like "Killing animals will have a bad effect on your Karma!"
  or "According to the indians, cows are holy! So don't eat them!"
  may motivate some people to care about animals, but I'm not very comfortable with these kinds of arguments.
</p>
<p>
  For one thing, these arguments are not about animals but rather about something different, namely religion or self-interest.
  But I think that we should treat animals well, not because some of them are holy or because it is in our own interest to do so, but because <b>suffering is bad</b> and <b>we shouldn't cause suffering unnecessarily</b>.
</p>
<p>
  That being said, I think we should avoid making arguments that have the potential to "backfire".
  For instance, the "Cows are holy"-example seems to imply that some animals aren't holy.
  And the undesirable effect will be that some people may care about cows but not about other animals.
</p>

<%= link_to language.name, Rails.configuration.host.to_s + language.abbreviation + "/" + request.env['PATH_INFO'], class:"dropdown-item" %>
<%= link_to language.name, root_path(locale: language.abbreviation), class:"dropdown-item" %>


<div class="text-center p-2 fixed-bottom navbar navbar-dark bg-dark">
  <%= link_to root_path do %>
      <div class="navbar-brand mx-auto d-inline">| Veggie Databse |</div>
  <% end %>

  <%= link_to impressum_path do %>
      <div class="navbar-brand d-inline">| Impressum |</div>
  <% end %>
</div>

app/views/arguments/adminpanel.html.erb
<p id="notice"><%= notice %></p>

<h1>Unpublished Arguments</h1>

<div class="jumbotron">
  <table class="table table-striped">

    <tbody>
    <% @unpublishedarguments.each do |argument| %>
        <tr>
          <td><%= argument.title %></td>
          <td><%= link_to 'Show', argument %></td>
          <td><%= link_to 'Edit', edit_argument_path(argument) %></td>
          <td><%= link_to 'Destroy', argument, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <td><%= argument.published %> <%= link_to 'Publish', publish_argument_path(argument), method: :post %></td>
        </tr>
    <% end %>
    </tbody>
  </table>

<h1>Unpublished Questions: </h1>
  <table class="table table-striped">

    <tbody>
    <% @unpublishedquestions.each do |argument| %>
        <tr>
          <td><%= argument.question %></td>
          <td><%= link_to 'Show', argument %></td>
          <td><%= link_to 'Edit', edit_question_path(argument) %></td>
          <td><%= link_to 'Destroy', argument, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <td><%= argument.published %> <%= link_to 'Publish', publish_question_path(argument), method: :post %></td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

<h1>All arguments </h1>
<table class="table table-striped">

  <tbody>
  <% @arguments.each do |argument| %>
      <tr>
        <td><%= argument.title %></td>
        <td><%= link_to 'Show', argument %></td>
        <td><%= link_to 'Edit', edit_argument_path(argument) %></td>
        <td><%= link_to 'Destroy', argument, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= argument.published %> <%= link_to 'Publish', publish_argument_path(argument), method: :post %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<h1>All Questions: </h1>
  <table class="table table-striped">

    <tbody>
    <% @questions.each do |argument| %>
        <tr>
          <td><%= argument.question %></td>
          <td><%= link_to 'Show', argument %></td>
          <td><%= link_to 'Edit', edit_question_path(argument) %></td>
          <td><%= link_to 'Destroy', argument, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <td><%= argument.published %> <%= link_to 'Publish', publish_question_path(argument), method: :post %></td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/arguments/index.html.erb
<%= render 'argumentsearchform' %>

app/views/arguments/show.html.erb
<p id="notice"><%= notice %></p>

<div class="jumbotron">
  <p class="text-center">
    <i><%= link_to @argument.parent.question, question_path(@argument.parent) %></i>
  </p>

  <hr />

    <%=  render partial: "arguments/argument", locals: {argument: @argument} %>

</div>