config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  devise_for :models

  scope "(:locale)", locale: /en|de|fr/ do
    root 'static_pages#welcome'

    resources :questions
    resources :arguments
    resources :images
    get '/adminpanel', to: 'arguments#adminpanel'
    get '/visits', to: 'static_pages#visits'
    get '/contact', to: 'static_pages#contact', as: 'contact'
    get '/contribute', to: 'static_pages#contribute', as: 'contribute'
    get '/use', to: 'static_pages#use', as: 'use'
    get '/overview', to: 'static_pages#overview', as: 'overview'
    get '/impressum', to: 'static_pages#impressum', as: 'impressum'
  end



  post "/arguments/publishargument/:id", to: 'arguments#publishargument', as: 'publish_argument'
  post "/questions/publishquestion/:id", to: 'questions#publishquestion', as: 'publish_question'

  post "/arguments/submitsuggestion/:id", to: 'arguments#submitsuggestion', as: 'submit_suggestion'

  post "/arguments/search", to: 'arguments#search'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_language.html.erb
<li class="nav-item">
  <div class="nav-link">
      <%= Language.model_name.human %>:
    <div>
</li>

<li class="nav-item">
  <div class="dropdown mt-1">
    <button class="btn btn-sm btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <%= Language.find_by_abbreviation(I18n.locale.to_s).name %>
    </button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
      <% Language.all.each do |language| %>
        <% unless I18n.locale.to_s == language.abbreviation %>
          <%# link_to language.name, url_for(locale: language.abbreviation), class:"dropdown-item" %>
          <%= link_to language.name, request.query_parameters.merge({:locale => language.abbreviation}), class:"dropdown-item" %>
        <% end %>
      <% end %>
    </div>
  </div>
</li>

app/views/layouts/_login.html.erb
<% if user_signed_in? %>
      <li class="nav-item">
        <%= link_to('Logout', destroy_user_session_path, method: :delete, class:"nav-link") %>
      </li>
      <li class="nav-item">
        <%= link_to('Edit registration', edit_user_registration_path, class:"nav-link") %>
      </li>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @title || "Let's be better to animals. A database of arguments for animal welfare." %></title>
    <%= csrf_meta_tags %>
    <%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-4">
    <%= link_to root_path do %>
        <div class="navbar-brand d-inline">Veggie Database</div>
    <% end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to t('browse'), arguments_path, class:"nav-link"  %>
        </li>
        <li class="nav-item">
          <%= link_to t('use_this_database'), use_path, class:"nav-link"  %>
        </li>
        <li class="nav-item">
          <%= link_to t('contribute'), contribute_path, class:"nav-link"  %>
        </li>
        <li class="nav-item">
          <%= link_to t('contact'), contact_path, class:"nav-link"  %>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto mr-5">
        <%=  render partial: "layouts/language" %>
        <%=  render partial: "layouts/login" %>
      </ul>
    </div>
  </nav>


  <div class="container">
    <%= yield %>
  </div>

  <div class="my-4">
    &nbsp;
  </div>

<footer class="footer bg-dark">
  <div class="text-center">
   <%= link_to "Impressum", impressum_path %> |
    <%= link_to t('contact'), contact_path %> 
  </div>
</footer>

  </body>
</html>

app/views/layouts/pdf.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title>PDF</title>
  <%= wicked_pdf_stylesheet_link_tag "application" -%>
</head>
<body>

  <div class='container'>
    <%= yield %>
  </div>

</body>
</html>